Сравниваются разные ML-модели, итоговая модель сохраняется в файл, где она потом применяется роботом в стратегии для предсказания.

In [1]:
import pandas as pd

In [2]:
%run prepare_data.ipynb

In [3]:
df = pd.read_csv('sber_data.csv')
df['time'] = pd.to_datetime(df['time'])
df.rename(columns={'time': 'Datetime', 'open':'Open','close':'Close', 'high':'High', 'low':'Low', 'volume':'Volume'}, inplace=True)

In [4]:
df

        Open  High  Close  Low                  Datetime  Volume
0        215   215    215  215 2023-04-04 14:23:00+00:00    1067
1        215   215    215  215 2023-04-04 14:24:00+00:00    6009
2        215   215    215  215 2023-04-04 14:25:00+00:00   11561
3        215   215    215  215 2023-04-04 14:26:00+00:00    4514
4        215   215    215  215 2023-04-04 14:27:00+00:00   10858
...      ...   ...    ...  ...                       ...     ...
411449   269   269    269  269 2024-09-25 14:19:00+00:00    6587
411450   269   269    269  269 2024-09-25 14:20:00+00:00   17085
411451   269   269    269  269 2024-09-25 14:21:00+00:00    5925
411452   269   269    269  269 2024-09-25 14:22:00+00:00    3549
411453   269   269    269  269 2024-09-25 14:23:00+00:00    7834

[411454 rows x 6 columns]

In [5]:
data, new_columns = prepare_data(df, dividend_dates)
data

,target,Datetime,anomalies_price,anomalies_volume,Open_ratio_1,Open_log_diff_1,Open_momentum_3,Open_roc_3,Open_ema_3,Open_momentum_5,...,Volume_roc_3,Volume_ema_3,Volume_momentum_5,Volume_roc_5,Volume_ema_5,Volume_momentum_7,Volume_roc_7,Volume_ema_7,Close_macd,Close_tema
7,0,2023-04-04 14:30:00+00:00,False,False,1.0,0.0,0.0,0.00000,215.000000,0.0,...,-76.192669,5556.109375,-8976.0,-77.640343,6295.498400,1518.0,142.268041,6241.065796,0.000000,215.000000
8,0,2023-04-04 14:31:00+00:00,False,False,1.0,0.0,0.0,0.00000,215.000000,0.0,...,-66.008250,4920.554688,-229.0,-5.073106,5625.332266,-1724.0,-28.690298,5752.049347,0.000000,215.000000
9,0,2023-04-04 14:32:00+00:00,False,False,1.0,0.0,0.0,0.00000,215.000000,0.0,...,-71.818043,3380.277344,-9018.0,-83.053969,4363.554844,-9721.0,-84.084422,4774.037010,0.000000,215.000000
10,0,2023-04-04 14:33:00+00:00,False,False,1.0,0.0,0.0,0.00000,215.000000,0.0,...,-37.485493,2498.138672,-10990.0,-87.180708,3447.703230,-2898.0,-64.200266,3984.527758,0.000000,215.000000
11,0,2023-04-04 14:34:00+00:00,False,True,1.0,0.0,0.0,0.00000,215.000000,0.0,...,731.855309,19071.569336,29116.0,445.948844,14180.135486,24787.0,228.283293,11899.645818,0.000000,215.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411419,0,2024-09-25 13:49:00+00:00,False,False,1.0,0.0,1.0,0.37037,270.937500,0.0,...,-13.052920,9533.198724,-5773.0,-43.146487,9707.813564,7184.0,1698.345154,9384.987838,-0.048964,271.023438
411420,0,2024-09-25 13:50:00+00:00,False,False,1.0,0.0,0.0,0.00000,270.968750,0.0,...,184.510011,8816.599362,-18460.0,-69.503012,9171.875709,7498.0,1245.514950,9063.740879,-0.039072,271.011719
411421,0,2024-09-25 13:51:00+00:00,False,False,1.0,0.0,0.0,0.00000,270.984375,1.0,...,-74.261575,6342.799681,-4880.0,-55.777803,7404.250473,-9511.0,-71.083707,7765.055659,-0.030877,271.003906
411422,0,2024-09-25 13:52:00+00:00,False,False,1.0,0.0,0.0,0.00000,270.992188,0.0,...,-18.851058,6257.899840,3326.0,116.824728,6993.833649,-20387.0,-76.758283,7367.041744,-0.024104,271.000000
411423,0,2024-09-25 13:53:00+00:00,False,False,1.0,0.0,0.0,0.00000,270.996094,0.0,...,-79.888889,3943.449920,-13403.0,-89.163119,5205.555766,-7120.0,-81.380729,5932.531308,-0.018523,270.998535

In [6]:
new_columns

['anomalies_price',
 'anomalies_volume',
 'Open_ratio_1',
 'Open_log_diff_1',
 'Open_momentum_3',
 'Open_roc_3',
 'Open_ema_3',
 'Open_momentum_5',
 'Open_roc_5',
 'Open_ema_5',
 'Open_momentum_7',
 'Open_roc_7',
 'Open_ema_7',
 'High_ratio_1',
 'High_log_diff_1',
 'High_momentum_3',
 'High_roc_3',
 'High_ema_3',
 'High_momentum_5',
 'High_roc_5',
 'High_ema_5',
 'High_momentum_7',
 'High_roc_7',
 'High_ema_7',
 'Low_ratio_1',
 'Low_log_diff_1',
 'Low_momentum_3',
 'Low_roc_3',
 'Low_ema_3',
 'Low_momentum_5',
 'Low_roc_5',
 'Low_ema_5',
 'Low_momentum_7',
 'Low_roc_7',
 'Low_ema_7',
 'Close_ratio_1',
 'Close_log_diff_1',
 'Close_momentum_3',
 'Close_roc_3',
 'Close_ema_3',
 'Close_momentum_5',
 'Close_roc_5',
 'Close_ema_5',
 'Close_momentum_7',
 'Close_roc_7',
 'Close_ema_7',
 'Volume_ratio_1',
 'Volume_log_diff_1',
 'Volume_momentum_3',
 'Volume_roc_3',
 'Volume_ema_3',
 'Volume_momentum_5',
 'Volume_roc_5',
 'Volume_ema_5',
 'Volume_momentum_7',
 'Volume_roc_7',
 'Volume_ema_7',
 'Close_macd',
 'Close_tema']

In [7]:
data['Datetime'] = pd.to_datetime(data['Datetime'])

# Определяем дату начала тестовой выборки (последний месяц)
test_start_date = data['Datetime'].max() - pd.DateOffset(months=1)

# Определяем дату начала валидационной выборки (предпоследний месяц)
val_start_date = data['Datetime'].max() - pd.DateOffset(months=2)

# Разделение данных на тренировочную, валидационную и тестовую выборки по времени
train_data = data[data['Datetime'] < val_start_date]  # все, что до предпоследнего месяца
val_data = data[(data['Datetime'] >= val_start_date) & (data['Datetime'] < test_start_date)]  # предпоследний месяц
test_data = data[data['Datetime'] >= test_start_date]  # последний месяц

# Признаки, которые будем использовать
features = new_columns

# Разделение на признаки (X) и целевую переменную (y) для каждой выборки
X_train = train_data[new_columns]
y_train = train_data['target']

X_val = val_data[new_columns]
y_val = val_data['target']

X_test = test_data[new_columns]
y_test = test_data['target']

In [8]:
from sklearn.metrics import precision_score, recall_score, accuracy_score, f1_score


def calculate_metrics_table(y_true, y_pred_prob, thresholds=[0.5, 0.6, 0.7, 0.8]):
    metrics_table = []

    for threshold in thresholds:
        y_pred = (y_pred_prob >= threshold).astype(int)
        metrics = {
            'Cutoff': threshold,
            'Precision': precision_score(y_true, y_pred),
            'Recall': recall_score(y_true, y_pred),
            'Accuracy': accuracy_score(y_true, y_pred),
            'F1-Score': f1_score(y_true, y_pred)
        }
        metrics_table.append(metrics)

    return pd.DataFrame(metrics_table)*100

In [9]:
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
import catboost as cb
from sklearn.metrics import roc_auc_score
from concurrent.futures import ThreadPoolExecutor

# 1. Применение StandardScaler к тренировочной, валидационной и тестовой выборкам
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
 
# Трансформируем валидационную и тестовую выборки
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

# Обучение модели model на обучающей выборки, predict_proba для предсказаний на валидационной и тестовой выборках
def train_and_predict(model, X_train, y_train, X_val, X_test):
    model.fit(X_train, y_train)
    pred_val = model.predict_proba(X_val)[:, 1]
    pred_test = model.predict_proba(X_test)[:, 1]
    return pred_val, pred_test, model.__class__.__name__

# Случайный лес с 100 деревьями и максимальной глубиной 5.
rf_model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)
# Одно дерево решений с максимальной глубиной 4.
dt_model = DecisionTreeClassifier(max_depth=4, random_state=42)
# Логистическая регрессия с L2-регуляризацией и параметром C=10.0
lr_model = LogisticRegression(solver='saga', penalty='l2', C=10.0, random_state=42)

# Градиентный бустинг на деревьях 
cb_model = cb.CatBoostClassifier(
    n_estimators=1000,
    random_state=42,
    learning_rate=0.1,
    l2_leaf_reg=3.0,
    bagging_temperature=1.0,
    rsm=0.8,
    subsample=0.8,
    verbose=0
)

# Используем ThreadPoolExecutor для параллельного обучения моделей в разных потоках
with ThreadPoolExecutor() as executor:
    futures = [
        executor.submit(train_and_predict, rf_model, X_train_scaled, y_train, X_val_scaled, X_test_scaled),
        executor.submit(train_and_predict, dt_model, X_train_scaled, y_train, X_val_scaled, X_test_scaled),
        executor.submit(train_and_predict, lr_model, X_train_scaled, y_train, X_val_scaled, X_test_scaled),
        executor.submit(cb_model.fit, X_train_scaled, y_train, eval_set=(X_val, y_val), early_stopping_rounds=50)
    ]

    # Ждем завершения всех потоков
    results = [future.result() for future in futures[:-1]]  
    cb_future = futures[-1]

    cb_future.result()  
    cb_pred_val = cb_model.predict_proba(X_val_scaled)[:, 1]
    cb_pred_test = cb_model.predict_proba(X_test_scaled)[:, 1]
    results.append((cb_pred_val, cb_pred_test, 'CatBoostClassifier'))
    
for pred_val, pred_test, model_name in results:
    roc_auc = roc_auc_score(y_val, pred_val)
    # Для валидационной выборки
    print(f"{model_name} ROC AUC VAL : {roc_auc}")
    roc_auc = roc_auc_score(y_test, pred_test)
    # Для тестовой
    print(f"{model_name} ROC AUC TEST: {roc_auc}")

/home/olga/ML/Projects/HW/homework-test/hw4/.venv/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

RandomForestClassifier ROC AUC VAL : 0.7588013097004161
RandomForestClassifier ROC AUC TEST: 0.7287763922480051
DecisionTreeClassifier ROC AUC VAL : 0.7137795574292077
DecisionTreeClassifier ROC AUC TEST: 0.6969740803750168
LogisticRegression ROC AUC VAL : 0.7272853457875789
LogisticRegression ROC AUC TEST: 0.6848293159517
CatBoostClassifier ROC AUC VAL : 0.7719435128056049
CatBoostClassifier ROC AUC TEST: 0.7467330924844561

Далее с помощью optuna находим лучшие гиперпараметры

In [ ]:
import optuna

# Функция для подбора гиперпараметров RandomForestClassifier
def objective_rf(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 500),
        'max_depth': trial.suggest_int('max_depth', 3, 20),
        'min_samples_split': trial.suggest_int('min_samples_split', 2, 10),
        'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 10),
        'max_features': trial.suggest_categorical('max_features', ['sqrt', 'log2', None]),
        'random_state': 42,
    }
    model = RandomForestClassifier(**params)
    model.fit(X_train, y_train)
    y_val_pred = model.predict_proba(X_val)[:, 1]
    auc = roc_auc_score(y_val, y_val_pred)
    return auc

In [ ]:
# Подбор гиперпараметров для RandomForestClassifier
study_rf = optuna.create_study(direction='maximize')
study_rf.optimize(objective_rf, n_trials=40, n_jobs=-1)
print("Лучшие параметры для RandomForestClassifier:", study_rf.best_params)
print("Лучший ROC AUC Score для RandomForestClassifier:", study_rf.best_value)

In [ ]:

# Функция для подбора гиперпараметров DecisionTreeClassifier
def objective_dt(trial):
    params = {
        'max_depth': trial.suggest_int('max_depth', 3, 20),
        'min_samples_split': trial.suggest_int('min_samples_split', 2, 10),
        'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 10),
        'max_features': trial.suggest_categorical('max_features', ['sqrt', 'log2', None]),
        'random_state': 42,
    }
    model = DecisionTreeClassifier(**params)
    model.fit(X_train, y_train)
    y_val_pred = model.predict_proba(X_val)[:, 1]
    auc = roc_auc_score(y_val, y_val_pred)
    return auc

In [ ]:
# Подбор гиперпараметров для DecisionTreeClassifier
study_dt = optuna.create_study(direction='maximize')
study_dt.optimize(objective_dt, n_trials=40, n_jobs=-1)
print("Лучшие параметры для DecisionTreeClassifier:", study_dt.best_params)
print("Лучший ROC AUC Score для DecisionTreeClassifier:", study_dt.best_value)

In [ ]:

# Функция для подбора гиперпараметров LogisticRegression
def objective_lr(trial):
    params = {
        'C': trial.suggest_loguniform('C', 1e-3, 10),
        'penalty': trial.suggest_categorical('penalty', ['l1', 'l2']),
        'solver': trial.suggest_categorical('solver', ['liblinear', 'saga']),
        'max_iter': trial.suggest_int('max_iter', 100, 1000),
        'random_state': 42,
    }
    model = LogisticRegression(**params)
    model.fit(X_train, y_train)
    y_val_pred = model.predict_proba(X_val)[:, 1]
    auc = roc_auc_score(y_val, y_val_pred)
    return auc

In [ ]:

# Подбор гиперпараметров для LogisticRegression
study_lr = optuna.create_study(direction='maximize')
study_lr.optimize(objective_lr, n_trials=40, n_jobs=-1)
print("Лучшие параметры для LogisticRegression:", study_lr.best_params)
print("Лучший ROC AUC Score для LogisticRegression:", study_lr.best_value)

In [ ]:

from catboost import CatBoostClassifier

def objective_cb(trial):
    params = {
        'iterations': trial.suggest_int('iterations', 100, 1000),
        'depth': trial.suggest_int('depth', 3, 10),
        'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
        'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
        'random_seed': 42,
        'verbose': 0,
        'early_stopping_rounds': 50
    }
    model = CatBoostClassifier(**params)
    model.fit(X_train, y_train, eval_set=(X_val, y_val), early_stopping_rounds=50, verbose=0)
    y_val_pred = model.predict_proba(X_val)[:, 1]
    auc = roc_auc_score(y_val, y_val_pred)
    return auc

study = optuna.create_study(direction='maximize')
study.optimize(objective_cb, n_trials=50, n_jobs=-1)

print("Лучшие параметры:", study.best_params)
print("Лучший ROC AUC Score:", study.best_value)

[I 2025-02-24 15:30:32,913] A new study created in memory with name: no-name-bd932fff-8842-4d03-ae2e-128148de92d0
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2025-02-24 15:31:10,261] Trial 11 finished with value: 0.7726411257584657 and parameters: {'iterations': 566, 'depth': 7, 'learning_rate': 0.22541262259852649, 'l2_leaf_reg': 2.1949770969442075}. Best is trial 11 with value: 0.7726411257584657.
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2025-02-24 15:31:15,415] Trial 12 finished with value: 0.7705441155311048 and parameters: {'iterations': 776, 'depth': 7, 'learning_rate': 0.1799523952813887, 'l2_leaf_reg': 0.004884533186189719}. Best is trial 11 with value: 0.7726411257584657.
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2025-02-24 15:31:21,796] Trial 6 finished with value: 0.7708470046340475 and parameters: {'iterations': 158, 'depth': 6, 'learning_rate': 0.14776313872233726, 'l2_leaf_reg': 0.0031904141103894445}. Best is trial 11 with value: 0.7726411257584657.
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2025-02-24 15:31:23,930] Trial 9 finished with value: 0.7714738037543512 and parameters: {'iterations': 950, 'depth': 7, 'learning_rate': 0.11234054106949998, 'l2_leaf_reg': 0.003234515067375459}. Best is trial 11 with value: 0.7726411257584657.
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2025-02-24 15:31:33,191] Trial 8 finished with value: 0.7690359892174841 and parameters: {'iterations': 330, 'depth': 5, 'learning_rate': 0.08765757530417156, 'l2_leaf_reg': 0.029686084333272213}. Best is trial 11 with value: 0.7726411257584657.
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2025-02-24 15:31:45,826] Trial 0 finished with value: 0.7728671204757925 and parameters: {'iterations': 404, 'depth': 8, 'learning_rate': 0.07903305026916982, 'l2_leaf_reg': 0.005239651546677927}. Best is trial 0 with value: 0.7728671204757925.
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2025-02-24 15:31:55,549] Trial 15 finished with value: 0.7726592978119655 and parameters: {'iterations': 887, 'depth': 8, 'learning_rate': 0.0647674257172859, 'l2_leaf_reg': 0.1607772863757445}. Best is trial 0 with value: 0.7728671204757925.
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2025-02-24 15:31:57,558] Trial 5 finished with value: 0.7703440638439178 and parameters: {'iterations': 303, 'depth': 5, 'learning_rate': 0.05870444608424425, 'l2_leaf_reg': 0.23964642715741288}. Best is trial 0 with value: 0.7728671204757925.
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2025-02-24 15:32:12,076] Trial 2 finished with value: 0.7707551400560684 and parameters: {'iterations': 723, 'depth': 10, 'learning_rate': 0.13829561189585948, 'l2_leaf_reg': 0.05276239622953353}. Best is trial 0 with value: 0.7728671204757925.
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2025-02-24 15:32:13,828] Trial 3 finished with value: 0.7679511747996426 and parameters: {'iterations': 352, 'depth': 3, 'learning_rate': 0.03859927188640688, 'l2_leaf_reg': 1.463726428483768}. Best is trial 0 with value: 0.7728671204757925.
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2025-02-24 15:32:35,407] Trial 16 finished with value: 0.771821702871065 and parameters: {'iterations': 346, 'depth': 7, 'learning_rate': 0.05659128907851678, 'l2_leaf_reg': 0.057920649242191674}. Best is trial 0 with value: 0.7728671204757925.
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2025-02-24 15:32:42,941] Trial 20 finished with value: 0.7670989576947634 and parameters: {'iterations': 794, 'depth': 3, 'learning_rate': 0.10828578048072934, 'l2_leaf_reg': 0.003160208472623069}. Best is trial 0 with value: 0.7728671204757925.
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2025-02-24 15:33:11,359] Trial 4 finished with value: 0.7721686871703115 and parameters: {'iterations': 237, 'depth': 9, 'learning_rate': 0.011889471204807905, 'l2_leaf_reg': 1.8554332603677057}. Best is trial 0 with value: 0.7728671204757925.
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2025-02-24 15:33:17,986] Trial 18 finished with value: 0.7722787337454586 and parameters: {'iterations': 927, 'depth': 9, 'learning_rate': 0.04487901705467725, 'l2_leaf_reg': 0.0011826199896002173}. Best is trial 0 with value: 0.7728671204757925.
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2025-02-24 15:33:18,599] Trial 24 finished with value: 0.7580834514392515 and parameters: {'iterations': 210, 'depth': 3, 'learning_rate': 0.011414999267172894, 'l2_leaf_reg': 0.04721516380733968}. Best is trial 0 with value: 0.7728671204757925.
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2025-02-24 15:33:38,355] Trial 21 finished with value: 0.7710672419675297 and parameters: {'iterations': 214, 'depth': 7, 'learning_rate': 0.010824724662209387, 'l2_leaf_reg': 0.19421949951669082}. Best is trial 0 with value: 0.7728671204757925.
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2025-02-24 15:34:23,246] Trial 7 finished with value: 0.7683118763890683 and parameters: {'iterations': 800, 'depth': 3, 'learning_rate': 0.012549329057859798, 'l2_leaf_reg': 1.8155357872660554}. Best is trial 0 with value: 0.7728671204757925.
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2025-02-24 15:34:47,957] Trial 17 finished with value: 0.7679771973791275 and parameters: {'iterations': 947, 'depth': 3, 'learning_rate': 0.031950193691308956, 'l2_leaf_reg': 3.0560625807066}. Best is trial 0 with value: 0.7728671204757925.
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2025-02-24 15:34:58,220] Trial 23 finished with value: 0.7678133505875863 and parameters: {'iterations': 591, 'depth': 3, 'learning_rate': 0.03678304078014083, 'l2_leaf_reg': 0.019512152136752555}. Best is trial 0 with value: 0.7728671204757925.
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2025-02-24 15:35:05,780] Trial 22 finished with value: 0.7731992091601866 and parameters: {'iterations': 729, 'depth': 9, 'learning_rate': 0.02261028468849202, 'l2_leaf_reg': 0.003668001171735448}. Best is trial 22 with value: 0.7731992091601866.
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2025-02-24 15:35:06,151] Trial 19 finished with value: 0.7719280901763419 and parameters: {'iterations': 820, 'depth': 9, 'learning_rate': 0.020664913913530043, 'l2_leaf_reg': 0.002145684592484}. Best is trial 22 with value: 0.7731992091601866.
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1e-3, 10),
[I 2025-02-24 15:35:20,326] Trial 14 finished with value: 0.7719512887540793 and parameters: {'iterations': 977, 'depth': 8, 'learning_rate': 0.017671986774588665, 'l2_leaf_reg': 0.0056414762066913995}. Best is trial 22 with value: 0.7731992091601866.
/tmp/ipykernel_349042/1448088619.py:7: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.3),
/tmp/ipykernel_349042/1448088619.py:8: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.

Лучшие параметры: {'iterations': 632, 'depth': 10, 'learning_rate': 0.01810593462956646, 'l2_leaf_reg': 0.9354075305966748}
Лучший ROC AUC Score: 0.7744025421584184

In [22]:
import catboost as cb

optimal_params = study.best_params
model = cb.CatBoostClassifier(
    **optimal_params,
    random_seed=42,
    verbose=0
)

model.fit(X_train_scaled, y_train, eval_set=(X_val, y_val), early_stopping_rounds=50, verbose=0)

In [23]:
y_train_pred_prob = model.predict_proba(X_train_scaled)[:, 1]
y_val_pred_prob = model.predict_proba(X_val_scaled)[:, 1]
y_test_pred_prob = model.predict_proba(X_test_scaled)[:, 1]

train_roc_auc = roc_auc_score(y_train, y_train_pred_prob)
val_roc_auc = roc_auc_score(y_val, y_val_pred_prob)
test_roc_auc = roc_auc_score(y_test, y_test_pred_prob)

In [24]:
print("\n=== Метрики для валидационной выборки ===")
print(f"ROC AUC: {train_roc_auc:.4f}")
calculate_metrics_table(y_train, y_train_pred_prob)

=== Метрики для валидационной выборки ===
ROC AUC: 0.7886

   Cutoff   Precision     Recall   Accuracy   F1-Score
0    50.0   66.169904  19.891317  84.222323  30.587679
1    60.0   73.011336  11.979428  83.843003  20.581861
2    70.0   87.263923   2.914396  82.958300   5.640416
3    80.0  100.000000   0.160114  82.551280   0.319716

In [25]:
print("\n=== Метрики для валидационной выборки ===")
print(f"ROC AUC: {val_roc_auc:.4f}")
calculate_metrics_table(y_val, y_val_pred_prob)

=== Метрики для валидационной выборки ===
ROC AUC: 0.7752

/home/olga/ML/Projects/HW/homework-test/hw4/.venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

   Cutoff  Precision     Recall   Accuracy   F1-Score
0    50.0  60.467980  11.563825  85.406896  19.414788
1    60.0  60.937500   0.918512  84.848376   1.809745
2    70.0  66.666667   0.047103  84.801833   0.094140
3    80.0   0.000000   0.000000  84.798253   0.000000

In [26]:
print("\n=== Метрики для тестовой выборки ===")
print(f"ROC AUC: {test_roc_auc:.4f}")
calculate_metrics_table(y_test, y_test_pred_prob)

=== Метрики для тестовой выборки ===
ROC AUC: 0.7480

/home/olga/ML/Projects/HW/homework-test/hw4/.venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

   Cutoff  Precision    Recall   Accuracy   F1-Score
0    50.0  52.477764  7.456220  81.478363  13.057224
1    60.0  53.571429  0.812421  81.367234   1.600569
2    70.0  40.000000  0.036108  81.343661   0.072150
3    80.0   0.000000  0.000000  81.347028   0.000000

In [27]:
model.save_model('current_model.cbm')